### ISSUE TITLE
Уточнение постановки задачи

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2017-2-paint#1]
Необходимо сформулировать общее представление о проекте — как будет выглядеть графический редактор и какими функциями он будет обладать. Полученное представление следует описать в README.md в виде одного или нескольких абзацев. После этого данную задачу можно закрывать.

**Comment by DrAleksan** [comment]
Добавил описание в README.md, но в части строк пропали переводы строк

**Comment by DrAleksan** [comment]
Исправлено

**Comment by Mazdaywik** [comment]
Если бы вы добавляли в сообщения коммитов #1, то ссылки на коммиты добавились бы на эту страницу между комментариев. Задачу закрываю, поскольку она выполнена.
